build:
  modules:
    - ninja
  dependencies:
    - ecmwf/ecbuild@develop
    - ecmwf/eckit@develop
    - ecmwf/fckit@develop
    - ecmwf/atlas@develop
    - ecmwf/eccodes@develop
    - ecmwf/plume@develop
  dependency_cmake_options:
    - ecmwf/atlas:-DENABLE_FORTRAN=ON
    - ecmwf/plume:-DPLUME_ENABLE_NWP_EMULATOR=ON -DPLUME_ENABLE_NWP_EMULATOR_SINGLE_PRECISION=ON -DPLUME_ENABLE_NWP_EMULATOR_DOUBLE_PRECISION=ON
  cmake_options:
    - -DPLUME_PLUGIN_EXTREME_EVENTS_ENABLE_NWP_EMULATOR_TESTS=ON
  parallel: 64