build:
  modules:
    - ninja
  dependencies:
    - ecmwf/ecbuild@develop
    - ecmwf/eckit@develop
    - ecmwf/fckit@develop
    - ecmwf/atlas@develop
    - ecmwf/eccodes@develop
    - ecmwf/plume@develop
  dependency_cmake_options:
    - ecmwf/atlas:-DENABLE_FORTRAN=ON
  parallel: 64